spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema?createDatabaseIfNotExist=true&useUnicode=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret-key: 1fa10329547167709d24b3287b742dd287233b6bf4d36604e924dba849d05cf9b6b1d69d1f2493f1b26c5c28fd8e9366187decd7be4c4c90585235b7a5d79338